### ISSUE TITLE
Research AngularJS organization

### ISSUE THREAD

**Issue by dotproto** [legitco/gimli#14]
Research and assemble a plan preliminary plan on how to organize the frontend aspect of this project.

**References**
- https://github.com/DaftMonk/fullstack-demo
- https://github.com/linemanjs/lineman-angular-template
- https://docs.angularjs.org/guide/unit-testing
- https://docs.angularjs.org/guide/e2e-testing

**Comment by kelsin** [comment]
Good references, we're working towards a good layout with other issues.
