### ISSUE TITLE
What github data would you like to see on each page for the logged in user?

### ISSUE THREAD

**Issue by kelsin** [legitco/gimli#19]
See title :smile:

**Comment by dotproto** [comment]
Thinking... For sure we'll need:
- username
- display name
- Gravatar icon
- link to user's account

Other things we may want (not limited to data provided in initial connect request).
- join date
- organizations
- last activity date for both issues and commits
- homepage
- email address
- stats for the number of repos, public gists, followers, following, stared items the user has
- contribution stats (total, longs streak, current streak
- issues stats

I'll keep thinking about this.

**Comment by kelsin** [comment]
The simple version of this data is implemented and we'll carry on getting more when we need :smile_cat:
