### ISSUE TITLE
Use Bower for client dependencies

### ISSUE THREAD

**Issue by dotproto** [legitco/gimli#20]
I suggest that we adopt Bower (bower.io) for client package management.

Ideologically I believe dependencies should be managed outside of the project itself. We already do this for the server with NPM; and I'd like to extend this to the client. I'm concerned about using NPM for client dependencies for a couple reasons:
- NPM requires you to install modules in node_modules
- NPM modules often include other modules. This adds unnecessary complexity (supporting code, files, bytes) to serving client modules.

Browserify may address these concerns, but Bower is a pretty quick win. Perhaps we can revisit this in the future and further simplify.

**Comment by mschnee** [comment]
This is going to depend on the extent of the dependencies we'll need on the front-end.  There are some advantages in baking everything necessary into a single, minified JS file, but there are also definitely advantages in keeping things separate.

In the HTTP2.0/SPDY world, bower would be my suggestion.  And if we're thinking about doing the "modern web" thing, that might be best.
