### ISSUE TITLE
Figure out how we want to test AngularJS

### ISSUE THREAD

**Issue by kelsin** [legitco/gimli#39]

**Comment by dotproto** [comment]
**Angular docs**
- AngularJS' [Unit Testing](https://docs.angularjs.org/guide/unit-testing) guide
- AngularJS' [End to End Testing](https://docs.angularjs.org/guide/e2e-testing) guide

**Projects**
- [Protractor](https://github.com/angular/protractor) - end to end test tool created by the Angular team
- [Test'em](https://github.com/airportyh/testem) - generic JS unit testing framework

**Relevant blog posts**
- [Getting Started With Angular Unit Tests](http://blog.freeside.co/post/41774841006/getting-started-with-angular-unit-tests) on Ad-Hockery
- [AngularJS–Part 8, More choice when testing](http://lostechies.com/gabrielschenker/2013/12/30/angularjspart-8-more-choice-when-testing/) on Los Techies

**Comment by dotproto** [comment]
Last night/this morning we just added [Karma](http://karma-runner.github.io/) support for Front End unit testing. At the moment we know _what_ we want to use (at least for now), but I think we could use some methodology to establish _how_ we do it.

**Comment by kelsin** [comment]
Testing framework is decided upon, now we need to hook up angular code coverage and fail on < 100%.
