### ISSUE TITLE
Research GitHub API capabilities

### ISSUE THREAD

**Issue by dotproto** [legitco/gimli#4]
We need to better understand what GitHub's API provides. Topics to consider include, but are not limited to
- Notifications
  - Marking notifications as read
  - Creating new notifications
- Subscribing to events
  - Creating issues
  - Comments on an issue
  - Closing issues
- Perform CRUD operations on a issues
- (un)read status for issues/comments

**Comment by kelsin** [comment]
We researched a bunch, we're going to close this in favor of focusing on features instead of unbounded research.
