### ISSUE TITLE
Markdown

### ISSUE THREAD

**Issue by kelsin** [legitco/gimli#6]
This looks like a nice node markdown engine. We probably want some sort of client side markdown rendering as well however? Would want to talk about this... but this node module does support github flavored markdown :+1: 

https://github.com/chjj/marked

**Comment by anthonynichols** [comment]
Are you using Jade? Jade has the ability to output Markdown (and others) using Filters: http://jade-lang.com/reference/#filters

**Comment by kelsin** [comment]
Do you know what library jade uses? Does it support GithubFlavoredMarkdown? What do we want to use for client side rendering? Does angular have a plugin or something for markdown?

**Comment by kelsin** [comment]
N/M Problem solved: https://developer.github.com/v3/markdown/
