### ISSUE TITLE
Gimli v0.1.0 -  Realtime Chat

### ISSUE THREAD

**Issue by dotproto** [legitco/gimli#70]
Hey all,

One of the major inspirations for Gimli is mobile messaging apps like WhatsApp and Facebook Messenger. For the first dev revision I think we should prove out this idea by making Gimli operate as a (near?) realtime messaging tool for GitHub Issues.

Once we have a first pas at this functionality we should start dogfooding it to make sure this isn't a terrible idea.

Thoughts? Does this seem like a reasonable goal for the first major milestone? If not, what would you rather focus on?

-Sim

**Comment by kelsin** [comment]
Yep, sounds like a good first milestone to me :smile:

**Comment by mschnee** [comment]
Seconded :)

**Comment by dotproto** [comment]
FYI I created a milestone and added this issue to it. Also, I finally found an Illustrator alternative that let me be productive enough to draft up a UI mock based on @mschnee's suggestion ~2 weeks back.

http://htmlpreview.github.io/?https://raw.githubusercontent.com/legitco/gimli-mockup/master/gimli-web-v0.1.0.svg

**Comment by brotkel** [comment]
The chat branch has an HTML wireframe for layout based on this mockup.

**Comment by kelsin** [comment]
Created a milestone for this :smile: removing the issue!
